model_path: "FastVideo/FastHunyuan-diffusers"
prompt: "A beautiful woman in a red dress walking down a street"
output_path: "outputs/"
num_gpus: 2
sp_size: 2
tp_size: 2
num_frames: 45
height: 720
width: 1280
num_inference_steps: 6
guidance_scale: 1
flow_shift: 17
seed: 1024
fps: 24
embedded_cfg_scale: 6
use_cpu_offload: false
disable_autocast: false
precision: "bf16"
vae_precision: "fp16"
vae_tiling: true
vae_sp: true
vae_config:
  load_encoder: false
  load_decoder: true
  tile_sample_min_height: 256
  tile_sample_min_width: 256
  tile_sample_min_num_frames: 16
  tile_sample_stride_height: 192
  tile_sample_stride_width: 192
  tile_sample_stride_num_frames: 12
  blend_num_frames: 5
  use_tiling: true
  use_temporal_tiling: true
  use_parallel_tiling: true
dit_config:
  prefix: "Hunyuan"
  quant_config: null
text_encoder_precisions:
  - "fp16"
  - "fp16"
mask_strategy_file_path: null
enable_torch_compile: false
