num_gpus: 2
model_path: FastVideo/FastHunyuan-diffusers
sp_size: 2 
tp_size: 2 
embedded_cfg_scale: 6 

"vae_precision": "fp16"
"vae_tiling": "True"
"vae_sp": "False"

"text_encoder_precision": "fp16"

"precision": "fp16"

inference_args:
  prompt: "A beautiful woman in a red dress"
  height: 720
  width: 1280
  num_frames: 45
  num_inference_steps: 6
  guidance_scale: 1.0
  flow_shift: 17
  seed: 1024
  fps: 24
  output_path: outputs_video/

vae_config:
  load_encoder: True
  load_decoder: True
  tile_sample_min_height: 256
  tile_sample_min_width: 256
  tile_sample_min_num_frames: 16
  tile_sample_stride_height: 192
  tile_sample_stride_width: 192
  tile_sample_stride_num_frames: 12
  blend_num_frames: 0
  use_tiling: True
  use_temporal_tiling: True
  use_parallel_tiling: True

dit_config:
  prefix: ""
  quant_config: ""

text_encoder_config:
  prefix: ""
  quant_config: ""
  lora_config: ""